--DDL

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	NomeEmpresa VARCHAR(20) NOT NULL 
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Marca VARCHAR(20) NOT NULL
)

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Modelo VARCHAR(20) NOT NULL
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	Placa VARCHAR(7) NOT NULL UNIQUE 
)

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE 
)

CREATE TABLE Aluguel 
(
	IdAluguel INT PRIMARY KEY IDENTITY NOT NULL,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	DataDeRetiro DATE,
	DataDevolucao DATE
)


