--DDL

USE HealthClinic_Tarde

CREATE TABLE TipoUsuario 
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(20) NOT NULL UNIQUE 
)

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTiposUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
	Email VARCHAR(50),
	Senha VARCHAR(25)
)

CREATE TABLE Paciente 
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	Nome VARCHAR(50) NOT NULL,
	DataNascimento DATE NOT NULL,
	Telefone CHAR(11) NOT NULL UNIQUE,
	RG CHAR(9) NOT NULL UNIQUE,
	CPF CHAR(11) NOT NULL UNIQUE,
	CEP CHAR(8) NOT NULL,
	Endereco VARCHAR(50) NOT NULL
)

CREATE TABLE Especialidade
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Clinica 
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(50) NOT NULL,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	RazaoSocial VARCHAR(50) NOT NULL,
	HoraAbertura TIME NOT NULL,
	HoraFechamento TIME NOT NULL,
	Endereco VARCHAR(50)
)

CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario),
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade),
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
	Nome VARCHAR(50),
	CRM CHAR(7)
)

CREATE TABLE Situacao
(
	IdSituacao INT PRIMARY KEY IDENTITY,
	Situacao BIT NOT NULL,
)

CREATE TABLE Consultas
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico),
	IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente),
	DataAgendamento DATE,
	Descricao VARCHAR(50),
	IdSituacao INT FOREIGN KEY REFERENCES Situacao(IdSituacao)
)







