CREATE DATABASE Exercicio_1_1;

USE Exercicio_1_1;

CREATE TABLE Pessoa 
(
	IdPessoa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CNH VARCHAR(11) NOT NULL UNIQUE 
)

CREATE TABLE Telefone 
(
	IdTelefone INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	Numero VARCHAR(20) NOT NULL UNIQUE 
)

CREATE TABLE Email
(
	IdEmail INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	Enderecos VARCHAR(30) NOT NULL UNIQUE
)

SELECT * FROM Email
SELECT * FROM Pessoa
SELECT * FROM Telefone

DELETE EMAIL WHERE IdEmail = 5