--DDL

CREATE DATABASE Exercicio_1_3

USE Exercicio_1_3

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY, 
	Raca VARCHAR(20) NOT NULL 
)

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	TipoPet VARCHAR(20) NOT NULL
)

CREATE TABLE Dono 
(
	IdDono INT PRIMARY KEY IDENTITY,
	NomeDono VARCHAR(20) NOT NULL
)

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet),
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
	Nome VARCHAR(20) NOT NULL,
	DataDeNascimento DATE NOT NULL
)

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco varchar(35) NOT NULL
)

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)
)

CREATE TABLE Atendente
(
	IdAtendente INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet)
)